 version: "1"
 services: 
  web:
    build: .    
    container_name: laragym_php
    volumes:
      - .:/var/www/laravel
      - ~/.env:/var/www/laravel/.env
    links:
      - redis
    working_dir: /var/www/laravel
  nginx:
    image: nginx:alpine
    container_name: laragym_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
    ports:
      - 8055:8055
  redis:
    image: redis:4.0.4-alpine
    container_name: laragym_redis
    volumes:
      - ~/redis_data:/data
